## Markov Processes

### Markov Chain - Continuing

These are the chains which have no terminations.

![Markov Chain](figs/mcchain_continuing.png "Markov Chain")

In [17]:
import numpy as np

In [18]:
# 2-state Markov Chain (non-episodic)

import numpy as np

# define transition probability matrix
P = np.array([[0.3, 0.7], [0.2, 0.8]])
print(f"Transition Matrix:\n{P}")

# define a random starting solution for state probabilities
# Here we assume equal probabilities for all the states
S = np.array([0.5, 0.5])

# run through 100 iterations to calculate steady state
# transition probabilities
for i in range(100):
    S = np.dot(S, P)
    if i % 5 == 0:
        print(f"Step {i}. State Probability vector S = {S}")


print(f"\nFinal Vector S={S}")

Transition Matrix:
[[0.3 0.7]
 [0.2 0.8]]
Step 0. State Probability vector S = [0.25 0.75]
Step 5. State Probability vector S = [0.2222225 0.7777775]
Step 10. State Probability vector S = [0.22222222 0.77777778]
Step 15. State Probability vector S = [0.22222222 0.77777778]
Step 20. State Probability vector S = [0.22222222 0.77777778]
Step 25. State Probability vector S = [0.22222222 0.77777778]
Step 30. State Probability vector S = [0.22222222 0.77777778]
Step 35. State Probability vector S = [0.22222222 0.77777778]
Step 40. State Probability vector S = [0.22222222 0.77777778]
Step 45. State Probability vector S = [0.22222222 0.77777778]
Step 50. State Probability vector S = [0.22222222 0.77777778]
Step 55. State Probability vector S = [0.22222222 0.77777778]
Step 60. State Probability vector S = [0.22222222 0.77777778]
Step 65. State Probability vector S = [0.22222222 0.77777778]
Step 70. State Probability vector S = [0.22222222 0.77777778]
Step 75. State Probability vector S = [0.222

### Markov Chain - Episodic


![Markov Chain Episodic](figs/mc_episodic.png "Markov Chain Episodic")

In [19]:
# MC Episodic

import numpy as np

# define transition matrix
P = np.array([
    [0.3, 0.5, 0.2, 0.0],
    [0.1, 0.9, 0.0, 0.0],
    [0.4, 0, 0, 0.6],
    [0, 0, 0, 1]
])

print(f"Transition Matrix:\n{P}")

# define any starting solution to state probabilities
S = np.array([1, 0, 0, 0])

# run through 1000 iterations to calculate steady state
# transition probabilities which should give prob ~ 1 for terminal state
for i in range(1000):
    S = np.dot(S, P)
    if i % 100 == 0:
        print(f"Step {i}. State Probability vector S = {S}")


print(f"\nFinal Vector S={S}")

Transition Matrix:
[[0.3 0.5 0.2 0. ]
 [0.1 0.9 0.  0. ]
 [0.4 0.  0.  0.6]
 [0.  0.  0.  1. ]]
Step 0. State Probability vector S = [0.3 0.5 0.2 0. ]
Step 100. State Probability vector S = [0.02146917 0.12918418 0.00436767 0.84497898]
Step 200. State Probability vector S = [3.90276420e-03 2.34836952e-02 7.93974834e-04 9.71819566e-01]
Step 300. State Probability vector S = [7.09462447e-04 4.26897424e-03 1.44332401e-04 9.94877231e-01]
Step 400. State Probability vector S = [1.28969351e-04 7.76033795e-04 2.62374085e-05 9.99068759e-01]
Step 500. State Probability vector S = [2.34446424e-05 1.41070997e-04 4.76955694e-06 9.99830715e-01]
Step 600. State Probability vector S = [4.26187505e-06 2.56445354e-05 8.67032023e-07 9.99969227e-01]
Step 700. State Probability vector S = [7.74743272e-07 4.66178173e-06 1.57613074e-07 9.99994406e-01]
Step 800. State Probability vector S = [1.40836399e-07 8.47440149e-07 2.86516303e-08 9.99998983e-01]
Step 900. State Probability vector S = [2.56018892e-08 1.

### Markov Reward Process - Continuing

Now the process has a reward for each transition in addition to the transition probabilities.

![Markov Reward Process](figs/mrp_continuing.png "Markov Reward Process")

In [20]:
# 2-state Markov Reward Process (non-episodic)

import numpy as np

# define transition probability matrix
P = np.array([[0.3, 0.7], [0.2, 0.8]])
print(f"Transition Matrix:\n{P}")

# define reward matrix
R = np.array([[-2,3],[0,2]])
print(f"Rewards Matrix:\n{R}")


Transition Matrix:
[[0.3 0.7]
 [0.2 0.8]]
Rewards Matrix:
[[-2  3]
 [ 0  2]]


In [21]:
import random
random.randint(0,1)

0

In [32]:
import random
gamma = 0.9
num_iterations = 100
Gt_list = {0:[], 1:[]} #dictionary of Gt values for each state
while True:
	chain_length = random.randint(2,20)
	trajectory = []
	#select start state (uniformly)
	s0 = random.randint(0,1)
	print(f'{s0} ',end='')
	trajectory.append([0,s0]) #start state

	s = s0 #current state, s
	for i in range(chain_length):
		#follow a transition using state transition probability
		if random.random() < P[s,0]:
			s_next = 0
			reward = R[s,0]
		else:
			s_next = 1
			reward = R[s,1]
		print(f'-> {s_next}',end = '')
		s = s_next #new current state
		trajectory.append([reward,s_next])
	print(f' [ Chain Length = {chain_length}]')

	#calculate Gt starting from the chosen start state
	t=0
	Gt = 0
	for t,[ri,si] in enumerate(trajectory):
		Gt = Gt + gamma**t * ri
	Gt_list[s0].append(Gt) #Gt at starting state=s0

	num_iterations -= 1

	if num_iterations == 0:
		break

1 -> 1-> 0-> 1-> 0-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1 [ Chain Length = 13]
1 -> 1-> 1-> 0-> 1-> 1-> 1-> 0-> 1 [ Chain Length = 8]
1 -> 0-> 1-> 1-> 1-> 1-> 1-> 1-> 1 [ Chain Length = 8]
0 -> 0-> 1-> 1-> 0-> 1-> 0-> 1-> 1-> 1-> 0-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 0-> 1-> 1 [ Chain Length = 20]
0 -> 0-> 0-> 1-> 1-> 1-> 1-> 1-> 1 [ Chain Length = 8]
0 -> 1-> 0-> 0-> 1-> 1-> 1-> 0-> 1-> 1-> 1-> 1-> 1 [ Chain Length = 12]
1 -> 1-> 1-> 1-> 1-> 0-> 1-> 1-> 0-> 0-> 1-> 1-> 1-> 1-> 1-> 0-> 0-> 1-> 1 [ Chain Length = 18]
1 -> 1-> 1-> 0-> 0-> 1-> 1-> 0-> 1-> 1-> 0-> 1-> 0-> 0-> 1-> 1-> 1-> 1-> 1-> 0-> 0 [ Chain Length = 20]
0 -> 1-> 1-> 1-> 1-> 0-> 0-> 0-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1 [ Chain Length = 18]
0 -> 1-> 1-> 1-> 1-> 1-> 1-> 0 [ Chain Length = 7]
0 -> 1-> 1 [ Chain Length = 2]
1 -> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 1-> 0-> 1-> 0 [ Chain Length = 18]
0 -> 1-> 1-> 1-> 0-> 0-> 0-> 0-> 1-> 1-> 1-> 0-> 1-> 0 [ Chain Length = 13]
0 -> 1-> 0-> 0-> 1-> 0-> 1-> 1-> 

In [33]:
Gt_list

{0: [11.166674734433055,
  4.140590220000001,
  9.410241753342,
  11.408832174654016,
  9.334062000000001,
  4.32,
  6.188432297643001,
  6.841859362904804,
  4.32,
  13.166729343342002,
  9.608031412880317,
  6.592876200000001,
  15.994464343880317,
  11.151590220000001,
  5.7780000000000005,
  5.644062,
  9.623893871107802,
  6.798745800000001,
  11.558568294060018,
  1.242,
  3.4002,
  15.95514325547288,
  6.12102168639632,
  4.32,
  13.5227415090078,
  5.5862856882,
  14.728333843062117,
  13.708819517756687,
  11.462889648296626,
  12.223487528425725,
  12.502063763574053,
  6.027318,
  14.628756006822057,
  15.758891319492285,
  13.429383918878703,
  7.751417580000001,
  8.271180000000001,
  13.0768049190078,
  4.389304608000001,
  -3.42,
  -0.6658379999999997,
  9.9129315090078,
  2.764152,
  8.60598783,
  9.533505836977922,
  12.21832398627,
  10.126268343342002,
  10.290655800000001,
  8.118615109369072,
  14.274210781050497],
 1: [11.8119315090078,
  8.92356363,
  9.26159022,

In [34]:
for s in [0,1]: #two states
	print(f'V(s={s}) = average of Gt = {np.mean(Gt_list[s])}')

V(s=0) = average of Gt = 8.858250200333153
V(s=1) = average of Gt = 9.732459367527321
